### ISSUE TITLE
"Python was not found" error with python installed via pyenv

### ISSUE THREAD

**Issue by Ryah** [fayaz12g/totk-aar#10]
Python was installed through [pyenv](https://github.com/pyenv/pyenv), and still is in PATH. Tried setting both a global and local python version.

Error log:
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "bGUI.py", line 139, in create_patch
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/Users/xxxxx/AppData/Roaming/yuzu/load/0100F2C0115B6000\\AAR MOD\\temp\\Common.Product.110.Nin_NX_NVN.blarc'

**Comment by fayaz12g** [comment]
A future version will not require python. Currently, this version requires python 3.11 from the Microsoft store

**Comment by fayaz12g** [comment]
New version no longer requires python
