### ISSUE TITLE
Map in quest menu appears somewhat duplicated.

### ISSUE THREAD

**Issue by xNicklaj** [fayaz12g/totk-aar#12]
Using 21:9 glitches out the map in quest menu. Here's a picture:
![yuzu_2023 06 05-09 05](https://github.com/fayaz12g/totk-aar/assets/40305701/bd4b8a7d-4e60-4b84-ac29-a3dff9c1a267)

**Comment by Gustour** [comment]
same for me in 21:9

**Comment by xNicklaj** [comment]
@fayaz12g has the issue been closed on purpose? It's still present in 5.2.2

**Comment by fayaz12g** [comment]
Reopened, sorry about that.

**Comment by Fruithapje21** [comment]
This issue has been fixed in v2.2.0 of TOTK-Ultrawide

**Comment by fayaz12g** [comment]
Fixed in 7.0.0
