### ISSUE TITLE
Geogliphs in the map are stretched.

### ISSUE THREAD

**Issue by xNicklaj** [fayaz12g/totk-aar#14]
As per title. The difference is quite noticable especially for the dagger and the pruna tablet.
![yuzu_2023 06 05-09 09](https://github.com/fayaz12g/totk-aar/assets/40305701/6056e019-7e27-4490-ae72-0763e751ad46)
![yuzu_2023 06 05-09 15](https://github.com/fayaz12g/totk-aar/assets/40305701/52ffa81b-a7ce-400c-b716-3f7aef10c7ed)

**Comment by fayaz12g** [comment]
This should be fixed for a week now, can you try again

**Comment by xNicklaj** [comment]
This issue is still present with the latest release

**Comment by fayaz12g** [comment]
Thank you for correcting me, I am reopening this

**Comment by Fruithapje21** [comment]
This issue has been fixed in v2.2.0 of TOTK-Ultrawide

**Comment by fayaz12g** [comment]
Fixed in 7.0.0
