### ISSUE TITLE
Corner or center HUD

### ISSUE THREAD

**Issue by Transcan** [fayaz12g/totk-aar#15]
What is the difference between corner or center hud? Can't see it.

**Comment by fayaz12g** [comment]
On aspect ratios below 16:9, aka vertical stretched ones, it does not make a difference. On wider ones, like 21:9, it puts the hud items like the mini map and other icons in the corner of the screen. Center keeps them in the 16:9 area

**Comment by Transcan** [comment]
Thats what I thought, but in my case it looks the same. I'm ussing 21:9 btw.
Corner enabled:
![image](https://github.com/fayaz12g/totk-aar/assets/2226763/1f40a799-a878-4f12-8b2a-e53329175af1)
Center enabled:
![image](https://github.com/fayaz12g/totk-aar/assets/2226763/2c4954a3-4887-4d6a-af60-abcdbc68097f)

**Comment by Transcan** [comment]
I said nothing...
I just deleted the whole the mod folder and recreated it again with the center version and now is behaving as expected.
Maybe I messed the files by overwriting one version with the other or I mixed them somehow.
Sorry for the bothering.

**Comment by fayaz12g** [comment]
All good! Thanks for the update
