### ISSUE TITLE
32:9 / 5120x1440 patching does not work

### ISSUE THREAD

**Issue by DaStivi** [fayaz12g/totk-aar#16]
not sure if i'm dooing something wrong, but when i try to patch for my resolution, no matter if centered or corner hud.... its not working... but also the xbox button layout is not working... game start's as if its nothing changed... ?!

status window reports successfull patch... had also some struggle with python.. needed to uninstall 3.10 version from windows store...

**Comment by fayaz12g** [comment]
What do you see in the main-version.pchtxt file? You can open in notepad. 
also, are you using stretch to window in yuzu?

**Comment by fayaz12g** [comment]
black screen fix is included. I'll write this on the ui so people don't have the same issue
