### ISSUE TITLE
Special Controls Dualsense

### ISSUE THREAD

**Issue by Gustour** [fayaz12g/totk-aar#18]
The special controls tutorial aren't well aligned on the Dualsense.

You can watch StavaasEVG's mod, he did it very well :
https://images.gamebanana.com/img/ss/mods/64760b24d9b1a.jpg

**Comment by fayaz12g** [comment]
A future version will merge his mod in, however currently his mod doesn't contain customizability of layouts

**Comment by fayaz12g** [comment]
It’s updated
