### ISSUE TITLE
Item descriptions are stretched

### ISSUE THREAD

**Issue by ShmylBlyck** [fayaz12g/totk-aar#19]
Descriptions on top of every item are stretched as shown in screenshot below :

![2023-06-06_19h52_51](https://github.com/fayaz12g/totk-aar/assets/135739819/00c515ab-b8e5-4ac1-ba91-53a6e119942d)

**Comment by fayaz12g** [comment]
This is a known issue and will be worked on

**Comment by fayaz12g** [comment]
Fixed in 5.2.2
