### ISSUE TITLE
Not a valid SARC file error

### ISSUE THREAD

**Issue by bonksmeister** [fayaz12g/totk-aar#2]
AAR 2.1.0
Aspect Ratio: 3440x1440
Controller Type: Playstation
Button Color: Colored
Button Layout: Normal
HUD Location: Corner

Console output:

> Traceback (most recent call last):
>   File "C:\Temp\AAR\download.py", line 4, in <module>
>     import requests
>   File "C:\Temp\AAR\requests\__init__.py", line 43, in <module>
>     import urllib3
> ModuleNotFoundError: No module named 'urllib3'
> 0070201E
> 0070201E
> Patch file created: C:/Temp\AAR MOD\exefs\main-1.0.0.pchtxt
> 0070201E
> 0070201E
> Patch file created: C:/Temp\AAR MOD\exefs\main-1.1.0.pchtxt
> 0070201E
> 0070201E
> Patch file created: C:/Temp\AAR MOD\exefs\main-1.1.1.pchtxt
> 0070201E
> 0070201E
> Patch file created: C:/Temp\AAR MOD\exefs\main-1.1.2.pchtxt
> Decompressed file: C:/Temp\AAR MOD\temp\Common.Product.110.Nin_NX_NVN.blarc
> Traceback (most recent call last):
>   File "C:\Temp\AAR\extract.py", line 80, in <module>
>     main(blarc_file_path, output_folder)
>   File "C:\Temp\AAR\extract.py", line 70, in main
>     extract(extracted_file_path, output_folder)
>   File "C:\Temp\AAR\extract.py", line 25, in extract
>     arc.load(inb)
>   File "C:\Temp\AAR\SarcLib\FileArchive.py", line 318, in load
>     raise ValueError('This is not a valid SARC file! Error code: %d' % result)
> ValueError: This is not a valid SARC file! Error code: 4
> Centered HUD value is set to  False
> The scaling factor is  0.7441860465116279
> Traceback (most recent call last):
>   File "C:\Temp\AAR\script.py", line 21, in <module>
>     file_names = os.listdir(blyt_folder)
>                  ^^^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/Temp\\AAR MOD\\temp\\Common.Product.110.Nin_NX_NVN\\blyt'
> Deleted old blarc file.
> Repacking new blarc file.
> Repacked new blarc file.
> Repacking new zs file.
> Compressed file: C:/Temp\AAR MOD\temp\Common.Product.110.Nin_NX_NVN.blarc.zs
> Repacked new zs file.
> Copied new zs file to mod.
> Removed temp folder.
> Complete! Enjoy the mod.

The mod did get generated, but using it in Ryujinx 1.1.855 yields the following error message:
> 00:00:00.031 |I| Configuration LogValueChange: ResScale set to: 2
> 00:00:00.035 |I| Configuration LogValueChange: ResScaleCustom set to: 1
> 00:00:00.035 |I| Configuration LogValueChange: MaxAnisotropy set to: 16
> 00:00:00.035 |I| Configuration LogValueChange: AspectRatio set to: Stretched
> 00:00:00.036 |I| Configuration LogValueChange: BackendThreading set to: Auto
> 00:00:00.036 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
> 00:00:00.037 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2208
> 00:00:00.037 |I| Configuration LogValueChange: AntiAliasing set to: SmaaUltra
> 00:00:00.038 |I| Configuration LogValueChange: ScalingFilter set to: Fsr
> 00:00:00.038 |I| Configuration LogValueChange: ScalingFilterLevel set to: 0
> 00:00:00.043 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.855
> 00:00:00.046 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
> 00:00:00.046 |N| Application Print: CPU: AMD Ryzen 5 5600X 6-Core Processor ; 12 logical
> 00:00:00.047 |N| Application Print: RAM: Total 16296 MiB ; Available 10760 MiB
> 00:00:00.049 |N| Application PrintSystemInfo: Logs Enabled: Error
> 00:00:00.049 |N| Application PrintSystemInfo: Launch Mode: UserProfile
> 00:00:00.188 |N| Application LoadApplication: Using Firmware Version: 16.0.2
> 00:00:12.479 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce RTX 3080 Ti (Vulkan v1.3.236, Driver v531.68.0.0)
> 00:00:41.710 |E| HLE.GuestThread.69 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
> 00:00:41.747 |E| HLE.GuestThread.69 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
>    at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 281
>    at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 212
>    at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 106
>    at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1253

There is no error if the mod is removed and replaced with aar_21-9_dualsense_pe version of the AAR mod in GameBanana.

**Comment by fayaz12g** [comment]
The issue has been fixed in 2.1.1
