### ISSUE TITLE
Does not work when there are multiple versions of Python installed

### ISSUE THREAD

**Issue by thaKnza** [fayaz12g/totk-aar#20]
I have the required version of python installed. I run the tool, the console says this:

Downloading zip file. This may take up to 10 seconds.
Controller type is Xbox-White-Western
Extracting zip.
Extracting ZS.
Extracting BLARC.
Patching BLYT.

But I don't get any mods in my output file. The tool creates the folder AAR MOD inside the output folder I specified but nothing else. On additional runs, it even claims to be deleting "old versions".

I checked to see if the tool was shoving stuff in appdata and it also is not doing that. I tried running the .exe as an administrator and that didn't help.

**Comment by fayaz12g** [comment]
Try v3.1 and let me know if that fixes it.

**Comment by fayaz12g** [comment]
3.3 seems to be working for others. Others have mentioned uninstalling older versions of python get it working.

**Comment by maybeageek** [comment]
Hi,
I have the same problem. However, I can't try 3.3 as Windows directly deletes the .exe as it sees a virus in it.

**Comment by thaKnza** [comment]
> 

I'll try 3.1.1 and see when I get off work tonight, but uninstalling other versions of python is not an option for me. I do have an older version installed but I need it for applications I rely on. This would be the first time it's been an issue for me to have more than one version of python installed. I'm not a python dev myself but my understanding is you can get around this using venv.

**Comment by maybeageek** [comment]
Update: My tests have been on a Windows 10. I can run 3.3.0 in my Windows 11 VM. However, it still does not create the Patch/Mod

**Comment by thaKnza** [comment]
Tested 3.1.1. It did not work. I will assume this is an issue around my python install. I really want this to work, but I really can't afford to go screwing with my Python 3.10.9 install to get this to work. I tried setting up a 3.11.0 virtual environment myself but I didn't have any luck with that. I probably didn't do it right, though. Not really sure what I did wrong but I only have so much time I can be messing with this stuff.

**Comment by stublu** [comment]
Having the same issue here. When I set the output folder it creates an AAR folder but when I click create patch it removes that folder and doesn't output anything.

**Comment by fayaz12g** [comment]
Yeah, it seems it is an issue with having multiple versions of Python. I understand people have other versions they cannot afford to replace--obviously I wouldn't want to break my other programs for a program I will use once. If you let me know what you want generated, I can do it for you on my end.

**Comment by maybeageek** [comment]
Also my issue was from one VM not having any python at all, and the other having multiple. So, a fresh VM with the right python resulted in the correct mod file. working great, thx.

**Comment by fayaz12g** [comment]
The new version should work without Python. Let me know if there are any issues
