### ISSUE TITLE
Getting "FileNotFoundError" [WinError 3] despite using Python 3.11 and not having any other installed

### ISSUE THREAD

**Issue by eldenlord12** [fayaz12g/totk-aar#21]
Hi, basically title. I get constantly this error that it cant find the path to the blarc and blyt files.

It says this in the console:

**_Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "GUI.py", line 87, in select_output_folder
NameError: name 'status_label' is not defined
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Temp\_MEI276682\download.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
0070201E
0070201E
Patch file created: C:/Users/username/Desktop\AAR MOD\exefs\main-1.0.0.pchtxt
0070201E
0070201E
Patch file created: C:/Users/username/Desktop\AAR MOD\exefs\main-1.1.0.pchtxt
0070201E
0070201E
Patch file created: C:/Users/username/Desktop\AAR MOD\exefs\main-1.1.1.pchtxt
0070201E
0070201E
Patch file created: C:/Users/username/Desktop\AAR MOD\exefs\main-1.1.2.pchtxt_**

and then this:

**_Input file not found.
Invalid BLARC file path.
Centered HUD value is set to  False
The scaling factor is  0.7619047619047619
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Temp\_MEI276682\script.py", line 21, in <module>
    file_names = os.listdir(blyt_folder)
                 ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] C:/Users/username/Desktop\\AAR MOD\\temp\\Common.Product.110.Nin_NX_NVN\\blyt'_**

and: 

**_Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "GUI.py", line 136, in create_patch
FileNotFoundError: [WinError 3] C:/Users/depp0/Desktop\\AAR MOD\\temp\\Common.Product.110.Nin_NX_NVN.blarc'_**

I did chose: 

Aspect Ratio: 21:9 
Controller: Playstation
Button Color: White
Layout: Western
HUD: Corner

But it really doesnt matter what I chose or if I run as admin or not. I ALWAYS get this error. It also doesnt matter if I download source code version or .exe. The location I chose as the output folder doesnt matter too. It gives me this error on desktop (as seen here) or in the Yuzu mods folder.

**Comment by fayaz12g** [comment]
Let me know if v3.1 fixes this. I will look into it

**Comment by eldenlord12** [comment]
Thanks for the quick response! Unfortunately I still get this same error with Python v3.10 from Windows store. I am using Windows 11 btw. if thats relevant.

**Comment by fayaz12g** [comment]
Which version of the utility are you using?

**Comment by fayaz12g** [comment]
You should be using https://github.com/fayaz12g/totk-aar/releases/tag/3.3.0

**Comment by eldenlord12** [comment]
Oh I am sorry, I was using a link from gamebanana which led me to version 2.0.1. Sorry for the confusion, it works with the version you linked.

**Comment by fayaz12g** [comment]
I linked an old version there as it was still in the process of being made. I’ll update my links. Glad you got it working
