### ISSUE TITLE
Can you add support/update to include newest Dualsense UI by Alerion921?

### ISSUE THREAD

**Issue by YaPoNeC** [fayaz12g/totk-aar#23]
In his latest version he added graphic for inactive buttons, that's the only thing missing and it will be just perfect.

Link to the mod: https://gamebanana.com/mods/443201

Thank you very much!

**Comment by fayaz12g** [comment]
Yes, it will be added this week

**Comment by fayaz12g** [comment]
Hey, so so sorry for not doing this sooner. I updated the latest ones now

**Comment by InterClaw** [comment]
Hi @fayaz12g,

I'm not getting the v12.x updates from Alerion921, for instance the inactive buttons. I'm using the white western layout, so for me it would be v12.3.

https://gamebanana.com/mods/443201#FileInfo_997130

This is how I have it selected in the tool.

![image](https://github.com/fayaz12g/totk-aar/assets/48981208/592ca1c5-3ff8-4918-8b25-b5eed9d79346)

I also tried generating it for the normal layout, which I assume would be using v12.2.

https://gamebanana.com/mods/443201#FileInfo_996568

**Comment by fayaz12g** [comment]
@InterClaw Thanks for bringing this to my attention, I will update this tonight

**Comment by fayaz12g** [comment]
@InterClaw I have now updated all the controller mods again, please let me know if this has fixed your issue

**Comment by InterClaw** [comment]
It's working now, thanks! 🎉
