### ISSUE TITLE
SteamDeck does not actually have a PE layout -- uses Normal layout instead

### ISSUE THREAD

**Issue by notoriousjere** [fayaz12g/totk-aar#25]
As of version 3.3.0, there is no SteamDeck UI for the PE layout. I assume the zips are ripped directly from here: https://gamebanana.com/mods/447721, where the dev has yet to release a PE layout version. You seem to have copied the Normal layout zip and renamed it PE (I unzipped did a diff of some of the files and they were the same between Normal/PE).

Interim solution: prevent the user from selecting this combination (a generic paradigm could be written to handle invalid combos).

Final solution: wait for the gamebanana mod author to create a PE layout for steam deck

**Comment by fayaz12g** [comment]
Yes this is accurate, the PE is the same as the normal layout for now. I've spoken with Alerion and ultimately want the program to dynamically create these modifications to the controller mods but it will take a lot of work. My current idea is unzipping the combined.bntx, and renaming the button icon files to match the layout requested, and then doing the same in the font files. But that is a far stretch goal and for now I will be creating a new controller selection interface that only lets you select what is possible.

**Comment by notoriousjere** [comment]
Sounds good!

**Comment by fayaz12g** [comment]
https://github.com/fayaz12g/totk-aar/releases/tag/dev720f fixes the issue (it is not in the release version yet as I'm waiting finish my GUI updates before making it a release, but it still fully works as intended)
