### ISSUE TITLE
Improved error reporting and console display

### ISSUE THREAD

**Issue by crudelios** [fayaz12g/totk-aar#28]
Hey, first and foremost, thanks for creating such an useful tool! 👍 

However, I have some usability qualms and I hope that these can be improved.

Sometimes there are errors that stop the tool from working.

Those don't get reported unless you are running the python files directly from the command line.

Ideally they would show up on the console and maybe also as a messagebox. That way the user knows the program isn't just stuck, it isn't actually doing anything anymore (because of the error).

Also, I think the console should display on every tab (or at least on the main tab) so there's instant feedback on the current state of the modding process. In that regard, I feel like both the console and the "Custom folder" button should go to the main tab instead of a separate one.

**Comment by fayaz12g** [comment]
Hey! For the updates going forward, I have removed the "noconsole" argument in pyinstaller so all errors will be displayed and full transparency of where it is getting stuck is there. I originally liked not displaying the console as it was neater but until it's 100% flawless you are right, it is useful for when users run into errors (which hopefully shouldn't happen till the next major release)
