### ISSUE TITLE
16:10 ratio is not work in 4.0.0, it is still 16:9 in the game.

### ISSUE THREAD

**Issue by TinyCK** [fayaz12g/totk-aar#29]
<img width="313" alt="屏幕截图 2023-06-15 172404" src="https://github.com/fayaz12g/totk-aar/assets/63989676/2862d96d-059d-4a5e-aa57-120b1a2bf028">
<img width="313" alt="屏幕截图 2023-06-15 172358" src="https://github.com/fayaz12g/totk-aar/assets/63989676/bd1add1b-b545-439a-9ea7-5c8e4de5afb2">
<img width="312" alt="屏幕截图 2023-06-15 172353" src="https://github.com/fayaz12g/totk-aar/assets/63989676/909fe6fb-4b75-4e20-a38b-157bc38a4a26">
<img width="313" alt="屏幕截图 2023-06-15 172349" src="https://github.com/fayaz12g/totk-aar/assets/63989676/49624c72-d68d-4b7a-adf0-94029a6ef58e">
<img width="314" alt="屏幕截图 2023-06-15 172254" src="https://github.com/fayaz12g/totk-aar/assets/63989676/e2323f05-e075-4432-8a22-e3078074fdf0">
I try the switch and xbox controller, for both 16:10 ratio is not work, and the program stucked without "Successed and enjoy". The 21:9 worked well.

**Comment by fayaz12g** [comment]
Thank you for finding this issue. I have fixed it in version 4.0.1, as a single line was missing in the vertical script to convert the scaling factor to a float
