### ISSUE TITLE
Map on Loading Screen is Stretched

### ISSUE THREAD

**Issue by thaikhoa** [fayaz12g/totk-aar#31]
Hey, idk if it's just me or it's an known issue, displaying map on loading screen seems stretching.

Cheers.

**Comment by fayaz12g** [comment]
Yes this is one of the few lasting known issues

**Comment by Fruithapje21** [comment]
I'm not sure whether it is possible to scale this map or not. But even if you can, it would leave a large empty space looking just as unnatural I think.

**Comment by thaikhoa** [comment]
It's okay to leave empty space as long as the map is in the right ratio.
Just let everything in the center.

**Comment by Fruithapje21** [comment]
I managed to render more of map in loading screen. It looks something like this now
![Screenshot 2023-07-18 132626](https://github.com/fayaz12g/totk-aar/assets/136446038/95641d7e-fff3-4ca9-9593-22959228ddbd)

**Comment by Fruithapje21** [comment]
This issue has been fixed in v2.3.0 of TOTK-Ultrawide

**Comment by fayaz12g** [comment]
@Fruithapje21 I just saw this, I really should enable notifications for GitHub. This is awesome, wonderful job. I’m not sure if you saw my last message to you, I wasn’t sure how to determine which pane lines up with which hex value so I can work on some more UI fixes as well (this one was going to be first on my list)

**Comment by fayaz12g** [comment]
Fixed in 7.0.0
