### ISSUE TITLE
3D scene aspect ratio not working in 4.1.0 (UI is OK)

### ISSUE THREAD

**Issue by InterClaw** [fayaz12g/totk-aar#33]
In 4.1.0 I got the unexpected problem that the 3D space does not get the aspect ratio change properly. For me this looks like 16:9 stretched to 21:9.

Whereas the UI is properly set to 21:9. So kind of the opposite of the early versions of your AR mod. :)

I tried it both by setting 3840x1600 and the more generic 21:9, but both display the same problems. Tried it with both "Playstation" and "Colored Dualsense" layouts as well (the latter is a no-go for me, since there's no western layout).

I did not touch the new graphics mod options however, since the way I interpreted it is that they're not active yet anyway? So I run those mods separately for now.

For now I went back to 4.0.2 where everything is ok, albeit with the older "Playstation" layout.

**Comment by gabriel-visualthinking** [comment]
Same issue happened to me.

**Comment by sanchez112929** [comment]
Same here

**Comment by thaikhoa** [comment]
On the same boat

**Comment by fayaz12g** [comment]
thank you all for reporting this. i will fix this later today, it seems the pchtxt file is not generating n properly after reworking it to suppor the new visual fixes

**Comment by fayaz12g** [comment]
I think it was a formatting issue. Please try 4.1.1

**Comment by InterClaw** [comment]
Looks good to me!
