### ISSUE TITLE
I used the 21:9 screen ratio, but it didn't reach it, and the edges were a little close

### ISSUE THREAD

**Issue by cprogpb** [fayaz12g/totk-aar#34]
I haven't touched python, but I'd like to try it, please ask what program your source code is packaged with
I would like to translate the GUI and post it on our country's community website, of course I will indicate the source
I can read some of the code, but I won't package and publish it

**Comment by cprogpb** [comment]
![Uploading 8ef29dbb92a921d592e46c211adca506.jpeg…]()

**Comment by cprogpb** [comment]
I haven't touched python, but I'd like to try it, please ask what program your source code is packaged with
I would like to translate the GUI and post it on our country's community website, of course I will indicate the source
I can understand some of the code, but I can't package it and publish it, and I don't know what commands and tools to use

**Comment by fayaz12g** [comment]
Hey I use pyinstaller to package

**Comment by cprogpb** [comment]
> 嘿，我使用 pyinstaller 打包

Thank you very much for your reply, can you be more specific, such as what command was used

**Comment by fayaz12g** [comment]
I’ve now included a txt file called make install. I run that entire command.
