### ISSUE TITLE
I used the 21:9 screen ratio, but it didn't reach it, and the edges were a little close

### ISSUE THREAD

**Issue by cprogpb** [fayaz12g/totk-aar#35]
I haven't touched python, but I'd like to try it, please ask what program your source code is packaged with
would like to translate the GUl and post it on our country's community website, of course will indicate the source
I can understand some of the code, but l can't package it and publish it, and l don't know what commands and tools to use

**Comment by dcbishop** [comment]
I'm not getting 32:9 either, seems to stay around 21:9

**Comment by fayaz12g** [comment]
@dcbishop im a little confused at the issue you are having . Please try the latest version and let me know what exactly is going wrong, is your emulator on stretch to window and is it not scaling the game?
