### ISSUE TITLE
Extracting Zip Hanging

### ISSUE THREAD

**Issue by SeeTurtlee** [fayaz12g/totk-aar#36]
Using the exe, it seems to stay extracting the zip forever. previous versions started nearly instantly  for me. I've tried many different optioon combos, changed its output folder, and also disabled my antivirus without any luck. 

![image](https://github.com/fayaz12g/totk-aar/assets/109108253/ecb8dc2d-7147-4491-be63-cc980902f2b8)

**Comment by SeeTurtlee** [comment]
New exe seems to have been uploaded and is working. Thank you!

**Comment by fayaz12g** [comment]
Hey @SeeTurtlee id reccomended using the latest version that supports all the visual fixes!
