### ISSUE TITLE
Memories are stetched rather than kept 16:9 or cut

### ISSUE THREAD

**Issue by xNicklaj** [fayaz12g/totk-aar#38]
![image](https://github.com/fayaz12g/totk-aar/assets/40305701/c84ee785-0582-4ffd-8f8a-24a87595bc51)

As you can see, using 21:9 aspect ratio (version 5.2.2) on Yuzu emulator, memories are stretched.

**Comment by fayaz12g** [comment]
Yes this is a duplicate issue with the cutscenes being stretched, it has to do with how videos are played. I could include inversely stretched videos with black bars but that would be make the mod very large (a few GB) so until we can find another way videos are stretched
