### ISSUE TITLE
Overscale after using 21:9 or 32:9 returning to 16:9

### ISSUE THREAD

**Issue by bannert1337** [fayaz12g/totk-aar#41]
When I use the 6.1.3 version, my game is overscaled so that image content is missing and cut.

**Comment by fayaz12g** [comment]
@bannert1337 Can you please provide an image detailing this? I haven’t seen this issue with anyone else and am wondering:
1) maybe the aspect ratio was flipped 
2) is yuzu set to stretch to window

**Comment by fayaz12g** [comment]
Hi, I'm reaching out again about this issue, I'm unsure what problem you are having especially since no one else is running into this. Please share more if you get the chance, or let me know if I can close the issue.

**Comment by bannert1337** [comment]
Hey, sorry for the late reply. I will describe the problem further below:
I have an LG C2 OLED and tried the 21:9 and 32:9 aspect ratio modes. For 21:9 I set the Aspect Ratio in Yuzu to “Force 21:9” and for 32:9 I set it to “Stretch to window” and created a new resolution for my TV with 3840×1080. Both of these worked exactly as expected. Now I returned to 16:9 and the many UI elements are over scaled. I already deleted the AAR and dFPS mods and generated new ones with the 16:9 settings, but still, the UI elements are over scaled.
These are all my settings in Yuzu:
![yuzu_WXme6xpvqX](https://github.com/fayaz12g/totk-aar/assets/58707896/fc8f816e-845a-4c46-976e-d6a6e89d837b)
![yuzu_eCi6JypFzc](https://github.com/fayaz12g/totk-aar/assets/58707896/29ba773a-f2dd-46c2-a083-ae881d4e2134)
![yuzu_CUaVgPuCUw](https://github.com/fayaz12g/totk-aar/assets/58707896/daa600e0-447a-46e7-a805-84b3857d11ff)
My TV is currently set to 3840x2160.
These are the settings in AAR I used:
![AAR_7 0 0_as64eXvNjQ](https://github.com/fayaz12g/totk-aar/assets/58707896/5ecf01d0-ace3-426a-b201-86342cbbffac)
![AAR_7 0 0_QAr13Qmy6Z](https://github.com/fayaz12g/totk-aar/assets/58707896/717e5087-c1f9-4648-95b0-d55df7999792)
![AAR_7 0 0_uoyAjZe7FS](https://github.com/fayaz12g/totk-aar/assets/58707896/4405b626-5be0-4fc7-9c05-c3e522b118dd)
![AAR_7 0 0_C5z16im65T](https://github.com/fayaz12g/totk-aar/assets/58707896/984a18d9-74d6-4fc1-a73e-af0cf5d2a07e)
Below are some screenshots that show the issue in Yuzu:
![yuzu_69N0kogd7M](https://github.com/fayaz12g/totk-aar/assets/58707896/7e56f397-2b3f-4f70-ae9b-32941b8c2dd5)
![yuzu_WrvE4IXqP7](https://github.com/fayaz12g/totk-aar/assets/58707896/5888e5a5-bf54-46e8-842a-ae933499897e)
![yuzu_EWJmH0HYqj](https://github.com/fayaz12g/totk-aar/assets/58707896/ba8d0a0d-108f-4c73-acac-3af6e6ac7720)
![yuzu_I51ZmoMZEC](https://github.com/fayaz12g/totk-aar/assets/58707896/994c7680-253b-4d27-8406-9e31cdce52fd)
![yuzu_7xsRfbSXTC](https://github.com/fayaz12g/totk-aar/assets/58707896/b660c97e-110f-4131-a5da-c52effe71299)
![yuzu_MMyQVbbuP9](https://github.com/fayaz12g/totk-aar/assets/58707896/2597debf-71c2-44a9-ab15-8378899e97a5)
![yuzu_zF3qe9UBw6](https://github.com/fayaz12g/totk-aar/assets/58707896/4e8fe85d-1792-48f7-902e-955ebfa7f8bf)

As you can see the UI elements are out of visible area, especially noticeable in the inventory.

**Comment by bannert1337** [comment]
With the mods AAR and dFPS disabled, the overscale is fixed:
![yuzu_z72paSlKB7](https://github.com/fayaz12g/totk-aar/assets/58707896/4f2bdd72-1631-4d5e-8b14-11b8200a1330)
![yuzu_vv6mpgZf06](https://github.com/fayaz12g/totk-aar/assets/58707896/a04c0eb3-a3b0-4d9a-94b9-62db6eb186d5)
![yuzu_M5iX2Xr60B](https://github.com/fayaz12g/totk-aar/assets/58707896/ef860376-1936-417d-ab83-514b0f559f39)
![yuzu_E5DIqhybpf](https://github.com/fayaz12g/totk-aar/assets/58707896/0dfd8b74-cf0d-41bc-9ae0-5dc08936aa8c)
![yuzu_2NTs7nZOuB](https://github.com/fayaz12g/totk-aar/assets/58707896/fe1dd119-77de-4c2d-9407-0e4a6288c655)

**Comment by fayaz12g** [comment]
Hi, thank you so much for explaining this further and documenting with photos. It seems this is happening because currently it passes it to either the vertical stretch script (being used here) or the horizontal stretch script. The former aspect ratios you mentioned of 21:9 and 32:9 work fine but when using 16:9, it is vertically shifting some of the elements due to the way the script works for steam deck now. I will add a hard coded edge case tomorrow for 16:9 that leaves the controller mod file untouched, but still generates the pchtxt and dfps.  Thank you for finding this

**Comment by fayaz12g** [comment]
The latest pre-release has addressed this issue: https://github.com/fayaz12g/totk-aar/releases/tag/dev721c
