### ISSUE TITLE
Purah Pad logo is stretched

### ISSUE THREAD

**Issue by fayaz12g** [fayaz12g/totk-aar#43]
Can be fixed by adding the following:

if name == 'AppMenuOverlay_00.bflyt':
# Scale N_Icon_00 (found in N_Fade_00, same location as the N_InOut_01)
× = float_to_hex(1/scaling_factor)
source_str = (4E5F49636F6E5F303000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803F)
replace_str = (4E5F49636F6E5F30300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000) + x
content = content.replace(source_str.lower(), replace_str.lower())

**Comment by Fruithapje21** [comment]
Should be just scaling_factor instead of the reciprocal. Correct version is up at TOTK-Ultrawide v2.4.0. Thank you for finding this.

**Comment by fayaz12g** [comment]
@Fruithapje21 thanks for helping me learn how to do hex editing, I woudnt have been able to find the fix without that

**Comment by fayaz12g** [comment]
https://github.com/fayaz12g/totk-aar/releases/tag/dev720f fixes the issue (it is not in the release version yet as I'm waiting finish my GUI updates before making it a release, but it still fully works as intended)
