### ISSUE TITLE
Stuck on “Creating custom ini” on dev720f

### ISSUE THREAD

**Issue by bannert1337** [fayaz12g/totk-aar#45]
![AAR_dev_M6KdwKXe5B](https://github.com/fayaz12g/totk-aar/assets/58707896/98c0a088-8f2d-4682-92f4-7ba1ae7f83f7)
![AAR_dev_zBk6bAC8pf](https://github.com/fayaz12g/totk-aar/assets/58707896/27622db3-3312-434d-b195-80fbb5263017)
![AAR_dev_Obw6v05oiG](https://github.com/fayaz12g/totk-aar/assets/58707896/2bb83700-b44e-4fe7-862a-e51358293f87)
![AAR_dev_RAS6RVV1Jm](https://github.com/fayaz12g/totk-aar/assets/58707896/393b6cd6-0ff3-4a25-a8b5-9e1315eb7f53)
![AAR_dev_WK7mIRSDCx](https://github.com/fayaz12g/totk-aar/assets/58707896/8fbab94c-0305-484f-b7c7-2f385597cb0e)
![AAR_dev_0gNzDNSKUP](https://github.com/fayaz12g/totk-aar/assets/58707896/eff9252c-6449-4fe7-8c56-1a92bb465586)

[dev720f_output_part1.zip](https://github.com/fayaz12g/totk-aar/files/12129478/dev720f_output_part1.zip)
[dev720f_output_part2.zip](https://github.com/fayaz12g/totk-aar/files/12129479/dev720f_output_part2.zip)

**Comment by fayaz12g** [comment]
Hey, thank you for making such a well documented issue. I'm not sure why GitHub was showing this dev version as the latest even though I had released dev721a and b last night that fixed this issue. Please try with the latest beta (https://github.com/fayaz12g/totk-aar/releases/tag/dev721c). It should work, but if not I will reopen accordingly
