### ISSUE TITLE
switch the location of dfps ini file

### ISSUE THREAD

**Issue by Gustour** [fayaz12g/totk-aar#48]
When setting config for dfps, the .ini file with the settings is into dfps mod and not into aar mod like it should be.
Into aar mod you put default.ini with all falue to 0, and into dfps mod you put our custom .ini with our value.
That could be a problem if we need many config for different devices.
Thanks
ps: i used 8.0.1

**Comment by fayaz12g** [comment]
This was intentional. I did this to ensure that if you disable the AAR Mod, you don’t lose your custom confirmation you created for dfps if that is still enabled. 

If you need different configs for different devices, you can specify the output folder to whatever you want and make it different for each device, and move the contents to that devices mod folder

**Comment by Gustour** [comment]
the things is that if you have many devices : 
- iphone 2556x1179, you set "aar mod phone" with those settings
- computer 3440x1440, you set "arr mod PC" with other settings
- Tv 3840x2160, "aar mod TV"
- ...
And when you open yuzu, you select one or other and it s done, nothing else to modify

**Comment by fayaz12g** [comment]
@Gustour I see, that makes a lot of sense, I will look into changing that later then. Would it also be handy to customize the mod name before generation?

**Comment by fayaz12g** [comment]
I've switched the places they generate in 8.1.2. I will look into customizing the name of the output mod as well in a future version

**Comment by Gustour** [comment]
Thanks a lot. Great idea for the name. Maybe use the resolution in the output mod folder.

**Comment by fayaz12g** [comment]
@Gustour My initial idea was dynamic naming, but having the aspect ratio and the controller type would make the name long, and that’s already forgetting a lot of the configured options, so I think I’ll let the user choose a name on the generate screen if they so wish

**Comment by Gustour** [comment]
@fayaz12g as you want it s your mod ;)
But as i user, i think we dont change many options between every resolutions because we used to like those we selected, maybe it s same for controler (pc or tv we will use same controler), and finally what really change is the resolution.
But let us choose is great too. Thanks
