### ISSUE TITLE
8.1 hangs on extracting zip 

### ISSUE THREAD

**Issue by atatassault** [fayaz12g/totk-aar#49]
When I run the utility, it generates a .ZIP file in the yuzu mods directory. So I think, well, every other mod here has to be a folder, so I'll extract it, and windows tells me it can't open it. I try opening with 7Zip as well, and 7Zip also tells me I can't open it.

**Comment by fayaz12g** [comment]
Hey, it should not be generating a zip file at all, what settings are you using? Did the console hang anywhere?

**Comment by atatassault** [comment]
I simply extract the mod to its own directory

I opened AAR_4.0.0.exe,
select Yuzu,
Under visuals: I enter 3440, 1440,
Controller Type: Xbox, Button Color: Colored, Button Layout: Western
HUD: Corner
Go back to the Generate page, hit generate.

And that's it. It makes the file named Xbox-Colored-Western.zip, plops in the Yuzu mod directory for TotK, 

The console log it creates is
Old mod found, deleting.
Old mod deleted.
Downloading zip file. This may take up to 10 seconds.
Controller type is Switch
Extracting zip file
Old mod found, deleting.
Old mod deleted.
Downloading zip file. This may take up to 10 seconds.
Controller type is Xbox-Colored-Western
Extracting zip file

**Comment by fayaz12g** [comment]
@atatassault 4.0.0 is very old version. Please try 8.1.0. In the future I will include an auto updater

**Comment by SeeTurtlee** [comment]
I'm having this issue on 8.1.0, it sems to hang on extracting zip forever

**Comment by fayaz12g** [comment]
@SeeTurtlee thanks for sharing, I’ll take a look at it. I’m assuming this wasn’t the case for 8.0.1? The difference is 8.1.0 includes new options for visuals

**Comment by SeeTurtlee** [comment]
@fayaz12g  8.0.1 worked fine. extracting almost was instant.

**Comment by fayaz12g** [comment]
@SeeTurtlee I’ll take a look at it later tonight, I’ll have a fixed version that correctly supports the new visual fixes out tomorrow

**Comment by atatassault** [comment]
... I did not realize there was a newer version, lol. The Game Banana page links to 4.0.0.

**Comment by fayaz12g** [comment]
@atatassault my fault, I should change that link to go to the releases page instead

**Comment by fayaz12g** [comment]
@SeeTurtlee @atatassault 8.1.1 is up now and works

**Comment by SeeTurtlee** [comment]
@fayaz12g working great! quick question though. What does the expand shutter size option under HUD do? I tried looking around but I may just be missing it.

**Comment by fayaz12g** [comment]
@SeeTurtlee It’s one of my things haha, basically current hud fixes stretch the scope from a circle to an oval which I thought looked a little wonky. I changed it back to a centered circle, but added it as an option to be an oval to “expand” the shutter size the stretch and fit the screen

**Comment by SeeTurtlee** [comment]
@fayaz12g Thanks for the explanation! Also sorry to complain about it again haha, but 8.1.4 is hanging at extracting zip again.

**Comment by fayaz12g** [comment]
@SeeTurtlee Noo I thought I fixed it haha, and don’t worry I appreciate you letting me know. I’ll take a look again, I thought I had tested it. What settings are you using so I can recreate

**Comment by SeeTurtlee** [comment]
@fayaz12g i use 21:9 (everything else unchecked) Nothing in legacy visuals. switch controller. Corner Hud. and yuzu

**Comment by fayaz12g** [comment]
@SeeTurtlee Thanks for the quick response, I’ll take a look and see what’s going wrong

**Comment by SeeTurtlee** [comment]
@fayaz12g fixed it. apparently having a VPN on prevents it from working. Sorry for the confusion!!

**Comment by fayaz12g** [comment]
@SeeTurtlee No worries! I’m wondering if the VPN was blocking the zip from being downloaded correctly

**Comment by SeeTurtlee** [comment]
@fayaz12g I gotta bother you again. It doesn't seem it was the VPN entirely. it said complete and seemed to unzip it fine. but when i go into the game, i get the black screen issue and everything seems streched.  So i played with the installer some more. and it seems the only way i can get it to "Work" is if expand shutter size is checked. if it isn't, it hangs. but even when i unpacks. it isn't installing right.

**Comment by fayaz12g** [comment]
@SeeTurtlee Just want to clarify, with expand shutter size set as false, it hangs at extracting zip, and with expand shutter size true, it generates but doesn’t actually work? In the generated pchtxt file does it have the right code?

Also, if you aren’t using any of the visual fixes, you can try an earlier version as the only changes I’ve made since 8.0.1 have to do with the visuals fixes
