### ISSUE TITLE
Script is calling python externally for all files instead of running them directly

### ISSUE THREAD

**Issue by crudelios** [fayaz12g/totk-aar#5]
Hello,

There seems to be a slight issue with the script, which may be causing problems to some users.

It seems you bundled everything as an executable. However, inside your main pyrhon scripts bundled in the executable, you're calling `python` directly for the sub-scripts (like `download.py`), which requires users to manually install python on top of your executable. In turn, that seems to require the proper dependencies to be installed regardless of them being bundled in the exe.

I don't know enough about python to provide an alternative to your approach, but maybe a simple thing like `import download` would work? That would at least prevent people from having to install python, while also avoiding dll conflicts.

**Comment by fayaz12g** [comment]
Hey! You are absolutely correct, I can change the way the python files are called, rather than opening them in python, I could import it as a subprocess and avoid the DLL conflict/need for python 3.11 installed. I will make these changes in a future version, but I am away from home this weekend

**Comment by fayaz12g** [comment]
This should be fixed now
