### ISSUE TITLE
Generation hangs on "Input file not found." (8.1.3)

### ISSUE THREAD

**Issue by InterClaw** [fayaz12g/totk-aar#52]
I do get further in the generation than on 8.1.0, but not all the way it seems still. The generation hangs on "Input file not found." in version 8.1.3.

Might this be because I'm using a custom output folder (the desktop)?

Here's the console log:

```
Old mod found, deleting.
If you are stuck hanging here, be sure to close the emulator first and then hit generate again.
Old mod deleted.
Getting Controller-ID
Set Controller-ID to Playstation-White-Western
Downloading zip file. This may take up to 10 seconds.
Extracting zip file. This can also take a few seconds.
Copying extracted files
Cleaning up old files
Extracting zip.
DynamicFPS Custom INI Generated
DynamicFPS Custom INI Generated
DynamicFPS Custom INI Generated
DynamicFPS Custom INI Generated
DynamicFPS Custom INI Generated
Ratio value is set to 2.4 and the scaling factor is 1.35.
0070201E
0070201E
Patch file created: C:/Users/InterClaw/Desktop\AAR MOD\exefs\main-1.0.0.pchtxt
Patch file created: C:/Users/InterClaw/Desktop\AAR MOD\exefs\main-1.1.0.pchtxt
Patch file created: C:/Users/InterClaw/Desktop\AAR MOD\exefs\main-1.1.1.pchtxt
Patch file created: C:/Users/InterClaw/Desktop\AAR MOD\exefs\main-1.1.2.pchtxt
Patch file created: C:/Users/InterClaw/Desktop\AAR MOD\exefs\main-1.2.0.pchtxt
Copying dynamicFPS mod.
Copied dynamicFPS mod.
Creating custom ini
Extracting ZS.
Input file not found.
```

And these are my settings:

![image](https://github.com/fayaz12g/totk-aar/assets/48981208/7c86a084-e50b-455d-b2eb-501413ddef83)

![image](https://github.com/fayaz12g/totk-aar/assets/48981208/f86093eb-fd1e-4044-a3ea-5281c5482d8f)

![image](https://github.com/fayaz12g/totk-aar/assets/48981208/4fa52219-bcb3-4d99-b9f3-bbc47596519f)

![image](https://github.com/fayaz12g/totk-aar/assets/48981208/caf90a60-eac2-4227-8a30-caef0dd1b6e4)

**Comment by fayaz12g** [comment]
@InterClaw ah shoot I completely forgot to test a custom output folder when building, I’ll check what’s wrong in the morning as it’s 3 AM for me. Thanks for reporting, I really appreciate how consistently fast you are with testing the tool

**Comment by fayaz12g** [comment]
@InterClaw It was bugging me that it wasn't working so I literally go out of bed and fixed it in the dark. Tested it too and it should work: https://github.com/fayaz12g/totk-aar/releases/tag/8.1.4

**Comment by InterClaw** [comment]
Thanks for fixing it again!
