### ISSUE TITLE
Updates to TOTK-Ultrawide

### ISSUE THREAD

**Issue by Fruithapje21** [fayaz12g/totk-aar#54]
I spend the day working on creating new fixes and cleaning up the code and managed to make quite some progress. Most notably might be the romfs script refactor to a version I used for debugging which makes adding changes much easier. I also updated the 16:10 script to work with any aspect ratio below 16:9. I also decided to do the proper math for once so there are no more hacky formulas for positioning shifted UI elements. This also made it possible to create a proper corner HUD for ultrawide. You may want to have look at the new source code.

**Comment by fayaz12g** [comment]
Oh awesome thank you for letting me know, I’ll take a look at it. Doing the actual math was on my todo list, as I allow aspect ratios below 16:9 on my tool but the corner hud toggle just uses the 16:10 shifting, so that’s a great change.

**Comment by fayaz12g** [comment]
Updates merged in 8.2.0
