### ISSUE TITLE
Black screen on launch after using version 8.4.1

### ISSUE THREAD

**Issue by bannert1337** [fayaz12g/totk-aar#58]
I updated to the newest version as usual and used the same settings. After starting TOTK, it stays black, fps stay at 1-2 and frame at 300-400+ ms. No matter how long I wait, the menu won't come up.
My AAR settings:
![AAR_8 4 1_wUTJgIjcEZ](https://github.com/fayaz12g/totk-aar/assets/58707896/5a8feb34-fa89-48ee-b66d-9eb1fa1bd29b)
I also noticed the generation process is incredibly fast, which might suggest that something is off.
With AAR version 8.3.0 the problem is gone.
![yuzu_umuBsFJTIP](https://github.com/fayaz12g/totk-aar/assets/58707896/9f1d2f79-55bf-46df-b207-46c1b345367a)

**Comment by SigonLegacy** [comment]
I plugged in all the same settings then started disabling things one by one (which is a pain in the behind given the sheer amount of shaders that load each time.) Was running into the same issue until I disabled "Disable Dynamic Resolution."

Re-enabled everything else and everything seemed to be alright.

Also note that it takes a good amount of time to generate on my system and that's with an i7-12700K and a Gen4 PCIe SSD.

**Comment by fayaz12g** [comment]
So sorry for not responding sooner, I've gotten quite busy over the last few days. As for this, thank you so much @SigonLegacy for troubleshooting, it seems when the Disable Dynamic Resolution code is left enabled in the pchtxt, it causes issue. It seems this value was not updated for version 1.2.0, so if you are using this version that could be the reason. Regardless. Disable Dynamic Resolution is not really needed anymore with the other patches like Disable Quality Reduction and Lod Improvement making a difference already, and it will likely be removed or moved to legacy patches after I update the value. I hope it works for you without that value being enabled @bannert1337
