### ISSUE TITLE
Trading menu is overstretched on 16:10 resolution

### ISSUE THREAD

**Issue by andy-kru** [fayaz12g/totk-aar#61]
Hello! I noticed this issue on my Steam Deck (16:10 resolution) with TOTK 1.2.0 and the latest AAR mod. It looks like a common issue for all traders in the game:
![0100f2c0115b6000_2023-07-30_19-59-47-964](https://github.com/fayaz12g/totk-aar/assets/45319374/8349cfeb-6654-4ec0-b19f-df33db458386)

**Comment by Fruithapje21** [comment]
Whoops, that's what happens when instead of shifting by 100px you scale by 100x.
Has been fixed in TOTK-Ultrawide v3.1.1. See [diff](https://github.com/Fruithapje21/TOTK-Ultrawide/commit/ffb5b73d2fcd754bbde54f207d7d47382740c29c).
