### ISSUE TITLE
Load/save stretching

### ISSUE THREAD

**Issue by InterClaw** [fayaz12g/totk-aar#63]
The changelog for 8.5.0 got me curious, so I spent some time comparing what it looks like when loading and saving the game in 8.4.1 and 8.5.0. I found some differences and things that don't look quite right. So I _think_ that you're not quite done yet with these adjustments and that you know this? Nevertheless, I thought I'd share what I found, so perhaps it can help with further fixes around this! 👍 

I also realize this is a lot of nitpicking over dialogs you spend a few seconds at, but since you started down this path I let the OCD flow here. 😅 Do with it as you please, hehe.

Below are the loading and saving processes in both 8.4.1 (left) and 8.5.0 (right). Saving has a few more steps it's going through pretty quickly, so I had to screen record and screenshot while pausing my video. All screenshots scaled down from 3840x1600 (2.4:1) to 50% and then cropped to the center 1000x800 pixels for comparison.

**1. Loading**

![841-850-loading](https://github.com/fayaz12g/totk-aar/assets/48981208/9a45bdb0-eaf1-428f-9470-563167cd40de)

_a. List_
- Both versions look exactly the same to me.
- Thumbnails seem to originally be my aspect ratio squished to approx. 2.22:1

_b. Confirmation dialog_
- Text is obviously squished in 8.5.0.
- Text indentation is wrong in both versions, unless how it looks in 8.4.1 is the original? But why would it be, because why whould it be different from how it looks in the list?
- Now the tumbnails are 2.1:1, so even more squished.
- The whole box is markedly narrower here as well. About 30% taller than in the list, but only a couple of percent wider. It's nice that it's a bit bigger when you're confirming, but it would be even nicer if the proportions were the same. 👍 Not sure how it is originally though. The slightly wider ones in the list do look better to me.

**2. Saving**

![841-850-saving](https://github.com/fayaz12g/totk-aar/assets/48981208/a6d86d2b-0c17-4443-b643-b5378402daa0)

_a. Confirmation dialog_
- Same comments as for 1b above.

_b. Saving... (1/3)_
- Text looks the same still as for 1b and 2a.
- The box is now about 33% wider. The thumbnail retains the 2.1:1 ratio still.
- Looking at it now, the "Saving..." overlay does look a little stretched perhaps? Not by much though. Probably less than 10%. The 5-pointed icon as well. Same thing in both versions.

_c. Saving... (2/3)_
- The contens of the box are now stretched to fill it, resulting in the 8.5.0 text now looking pretty correct to my eye (indentation aside), whereas in 8.4.1 the text is definitely overstretched.
- As a result, the thumbnail is overstretched to about 2.85:1 in both versions.
- I guess this is the tricky part to get this right since the thumbnail only occupies about 43% of the overall box, not half. (About 35% in in the list.) So I guess the size of this box needs to take the thumbnail proportions into consideration, while also considering how much the text should be stretched, so the end result looks correct at both ends. 😅 I guess that what you're going for is to have these wider boxes across the board, looking correct in all places based on the aspect ratio set in the tool? 😓

_d. Progress saved (3/3)_
- Here the text overlay has the same slight stretching as "Saving..." has above.

Some closing comments:
- 2b, 2c, and 2d are over in about a second, so perhaps not super important. It's more the lists and confirmation dialogs that you actually spend any real time looking at that are more relevant, so perhaps those are the ones to focus on?
- If it turns out to be tricky to get the width of these boxes just right, then perhaps don't change that at all and instead see if cropping the thumbnail to adapt to the aspect ratio of the current boxes could be another approach instead? So in my case, the 2.4:1 thumbnail would "fill" the 2.22:1 and 2.1:1 boxes respectively, not squish inside them. There are no UI elements in the thumbnails anyway, so you wouldn't really notice what's missing at the sides.
- Currently, both versions tested have their limitations. If I had to pick one right now, I'd say that 8.4.1 overall looks a bit better. The squished text is the reason for this. 😄 But as I wrote, I don't think you're quite done here yet...

**Comment by fayaz12g** [comment]
Hey! Thank you so so much for such a detailed report-- This was one of the biggest reasons I added you to the credits last night, you always do a great job testing and documenting issues :) Sorry I didn't respond sooner, I have an issue where if I plan too much of what to do or respond with, I never respond or push out changes, but I'm working on it. 

You are correct, the saving screen is a giant WIP, but I can say almost all of it is complete now and pushed to the latest version! Here what I fixed: 
![unknown_2023 08 07-14 49](https://github.com/fayaz12g/totk-aar/assets/61674751/1784b624-e6be-49a8-bb74-92f1408a7ed8)

Text is no longer squished in the preview, and the aspect ratio of the image is now correct to match the game. The buttons and text elements are all in line as well, in their correct positions. 

![unknown_2023 08 07-14 49_1](https://github.com/fayaz12g/totk-aar/assets/61674751/029d71c2-5f2d-4f16-9330-19dfd1dde0a6)
![unknown_2023 08 07-14 49_2](https://github.com/fayaz12g/totk-aar/assets/61674751/6ed089d9-8457-4671-ad89-39508055c0f8)

The saving text has been fixed as well as the Progress Saved text. Here is what I need to work on: 
![unknown_2023 08 07-14 48_1](https://github.com/fayaz12g/totk-aar/assets/61674751/193f3606-fa5f-4eb8-9966-7a9f16a7928b)

The SystemLoadList shows the game previews in their correct ratios, but the text elements and autosave icon are stretched with it. For some reason, the game has this all as one block and I'm not sure where it pulls it from, but I will keep looking! Let me know if you find anything else that looks off!

**Comment by InterClaw** [comment]
Tried it all out now again in version 8.6.5!

The aspect ratio in the load list does look correct. And as you say the text is stretched.

One interesting thing about this though is that the thumbnail viewport seems to be cropped down to 3:1. The top and bottom pixels are not showing in the screenshot. Since there are no UI elements in these screenshots/thumbnails, you don't really notice. But what you _do_ get to see, seems to have the right proportions at least.

![865 load 1](https://github.com/fayaz12g/totk-aar/assets/48981208/9bce66be-bd92-45fd-930b-1b007ad3da6d)

I compared it to a regular screenshot of the game world with the camera in the same position...

![865 world](https://github.com/fayaz12g/totk-aar/assets/48981208/359536ae-5ded-4ca5-8149-fe47b7ab17e9)

... and then center cropped that screenshot from 3840x1600 down to 3840x1280. To me it looks spot on to what I'm seeing in the thumbnails. Sans the UI.

![865 world 3to1](https://github.com/fayaz12g/totk-aar/assets/48981208/70013709-f532-41ba-a9bb-67efa5e972fd)

I guess they crop even regular 16:9 thumbnails this way to make them look more "cinematic" in the list perhaps. 😃 It is what it is.

I do however see something wrong in the confirmation dialogs (looks the same for both save and load).

![865 load 2](https://github.com/fayaz12g/totk-aar/assets/48981208/9cfe92f0-d1ef-4ef7-a7b8-9686feb526ca)

There is some extra space to the left seemingly. And the thumbnail viewport is here approx. 2.85:1.

But I don't think what is showing is squished or stretched. Instead I think the same screenshot is here cropped differently. Comparing to the 3:1 screenshot above I do see more at the bottom of the picture. So it crops the same amount at the top, but "not enough" at the bottom, to get the same 3:1 thumbnail. 😃 

Actually, if the thumbnail was to extend into the extra space on the left AND the equivalent amount on the right, then you'd arrive at that same 3:1 ratio. Here's a screenshot from GIMP to show you what I mean. The ratio of the selection showing in the status bar bottom left. So if it was to "zoom in" a bit more, losing pixels at the bottom, to fill that 3:1 space, then it would look the same as in the load list.

![865 confirmation 3to1](https://github.com/fayaz12g/totk-aar/assets/48981208/410fe8ec-98c1-4d5c-b389-3ddb4e83bd4b)

Beyond that, the overlay text and that animated icon look nice now! And the transition when the thumbnail goes away looks the same as the confirmation screen.

**Comment by fayaz12g** [comment]
I've made some changes to reduce that black space next to the box holding the image, hopefully that looks better

**Comment by InterClaw** [comment]
Tried it out not in 9.0.5. Definitely a lot better! It fills out the black space now. The confirmation is still 2.85:1, so it's cropped differently than the list that is 3:1. But these are dialogs you spend a few seconds at, so you're never gonna notice. 👍
