### ISSUE TITLE
Error when generating: local variable 'process_name' (8.5.2)

### ISSUE THREAD

**Issue by InterClaw** [fayaz12g/totk-aar#64]
Getting this error when trying to generate the mod:

![image](https://github.com/fayaz12g/totk-aar/assets/48981208/6c69e469-8e7a-419e-8bcb-ed341b135a8f)

I am using a custom output folder (the desktop). Perhaps this is causing a problem again? 😃

**Comment by fayaz12g** [comment]
Thank you for reporting this, I was missing an else statement, it had to do with how the program checks if the emulator is running. Fixed now!
