### ISSUE TITLE
White text on white background with Light app mode (8.5.2)

### ISSUE THREAD

**Issue by InterClaw** [fayaz12g/totk-aar#65]
With the new light theme I'm getting white text in these four boxes. Makes it kind of hard to see, hehe.

![image](https://github.com/fayaz12g/totk-aar/assets/48981208/426af5af-27e6-4bec-b84b-ebf1825bf7f3)

- Note that the default texts (like 1080 in the screenshot) shows up fine in gray though.
- The bottom two boxes are fine.
- If I set the app mode to dark, then I get the previous look and then the light text is fine. This is Windows 10 btw.

![image](https://github.com/fayaz12g/totk-aar/assets/48981208/7b76dbaa-d6c5-405c-b54a-44da9ce4ce8d)

**Comment by fayaz12g** [comment]
I noticed this, it's because of the gray text, when you type in the box it then changes the foreground color to white because it used to be only dark mode. I'll try to change it so make the text become the system default color instead

**Comment by fayaz12g** [comment]
I've now fixed it and merged it into main. I added a tuple that specifies different colors for light mode vs dark mode
