### ISSUE TITLE
Yuzu crashes with aspect ratios wider than 16:9 (8.6.2)

### ISSUE THREAD

**Issue by InterClaw** [fayaz12g/totk-aar#73]
When trying to launch the game with version 8.6.2, Yuzu 1518 crashes immediately if I've set a ratio like 21:9 or whatever. I think when it's trying to read in the mod.

Works like it should with 16:9, 16:10 etc.

Could it be related to this?
https://github.com/HolographicWings/TOTK-Mods-collection/issues/142#issuecomment-1667654756

**Comment by fayaz12g** [comment]
Hey, for some reason I'm not experiencing the same crashing but I'll test it on my friends system too. Also the issue you linked it something I updated yesterday, but it only applies to taller aspect ratios like 16:10.  Can you tell me what the settings you applied were

**Comment by fayaz12g** [comment]
I found the issue-- When doing code updates yesterday I pushed to github forgetting I had to update the version number for the program to actually download. Changed it from 8.6.2 to 8.6.3, should work now
