### ISSUE TITLE
Triple screen resolution not working

### ISSUE THREAD

**Issue by mkyt01** [fayaz12g/totk-aar#79]
I have a 1440p triple screen setup with a resolution of 7680x1440 or 7800x1440 with bezel compensation using nvidia surround.
I could not get 7800x1440 to launch even though that's my native resolution. 7680x1440 launched but it is just a pinched view confined to the middle screen. Tried on Yuzu 1580 and 1491. Also tried 5760x1080 and that wouldn't launch either.
Tried on Vulkan and OpenGL.
![image](https://github.com/fayaz12g/totk-aar/assets/147266147/da86770d-2a3c-44f2-8e94-06272e4c212c)
![image](https://github.com/fayaz12g/totk-aar/assets/147266147/42e8c6ec-5e92-42f0-96a8-37caaafbaa15)
![image](https://github.com/fayaz12g/totk-aar/assets/147266147/4c688a15-2b80-4362-a6de-dc4aab73eb8d)
![image](https://github.com/fayaz12g/totk-aar/assets/147266147/d4448021-c41b-4330-a3d0-44121345032e)

![image](https://github.com/fayaz12g/totk-aar/assets/147266147/57317477-c86a-462c-9679-54c3d5b7cff8)

**Comment by Fruithapje21** [comment]
Set `Aspect ratio` to _stretch to window_ in yuzu settings

**Comment by fayaz12g** [comment]
My assumption is yuzu is trying to run on just one screen. Are the monitors setup to be recognized as just one screen? I know nvidia and amd both have tools to do this. Also, if they're set to be used as extended displays, can you try making yuzu not be full screen and stretch the window across all three screens manually? With stretch to window as fruit said

**Comment by mkyt01** [comment]
I use Nvidia surround and both in Nvidia control panel and windows settings it shows up as a single screen. And on every other game the resolution just shows up just like a custom resolution. That's why I thought this mod "should" have worked. I don't know of a game that works on triple screen with separate screens just extended.
When I run the game with this mod, the game always stays in 16:9 ratio regardless of the settings or window format. 
Just the 16:9 part of the window has the game on it but stretched like in the picture I shared.
And when I try to extend the vertical size of the window, it stops at the height of my screen (1440)

**Comment by mkyt01** [comment]
Ok I just got it working. I think it was something to do with the mod generator setting or the new yuzu version.
It worked now with these settings:
![image](https://github.com/fayaz12g/totk-aar/assets/147266147/f75b8f1f-26ec-41c3-a04e-006711836760)

Now it's just that my resolution/quality in game is very bad.
I've set the mod generator resolution as it should and upped the shadow quality and the resolution in Yuzu is set to 2x or 4x, but it still looks more like 720p or worse:
![image](https://github.com/fayaz12g/totk-aar/assets/147266147/6e882f7e-a2dd-4466-a98c-e49d4d1a26a2)

**Comment by mkyt01** [comment]
It's like it makes the max resolution to be whatever it is stretched at 16:9, then just stretches that out without creating more quality to counteract the stretching. 
Compare the last pic which was in triple screen and then this which is exactly the same but on one screen.
![image](https://github.com/fayaz12g/totk-aar/assets/147266147/61d7dcae-aaa3-47fb-8a09-fb49cf270c88)
