### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified

### ISSUE THREAD

**Issue by QBKU** [fayaz12g/totk-aar#8]
AAR 3.0, Python 3.11.3, Win11-64.
Was trying toset "3440:1440" and Hud Location as "Center".

Error log:
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "bGUI.py", line 139, in create_patch
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'F:/Yuzu/user/load/0100F2C0115B6000\\AAR MOD\\temp\\Common.Product.110.Nin_NX_NVN.blarc'

**Comment by fayaz12g** [comment]
Did the controller file download correctly or did it fail to download? If you go to that location what do you see

**Comment by fnguyen-radiomobile** [comment]
Just wanted to note that I also ran into this issue, but I noticed that there were also python errors mentioning that packages failed to install (something about version mismatches). I had python 3.11 installed but also a couple other older python versions installed on my machine. After removing all versions of python on my machine and then reinstalling 3.11 via the microsoft store, the program worked without issue.

**Comment by IPaid4WinRAR** [comment]
I also ran into this issue, but I noticed that there were also python errors mentioning that packages failed to install (something about version mismatches). I had python 3.11 but also a couple other older python versions installed on my machine. I removed all versions of python on my machine and then reinstalled 3.11 via the microsoft store, and the program worked without issue.

**Comment by abhidash29** [comment]
@fayaz12g I just ran into this issue as well, looks like the problem is line 19 of `download.py`. Removing the line `sys.stdout = PrintRedirector(scrolled_text)` allowed it to download the controller zip file without throwing any exceptions.

**Comment by fayaz12g** [comment]
> @fayaz12g I just ran into this issue as well, looks like the problem is line 19 of `download.py`. Removing the line `sys.stdout = PrintRedirector(scrolled_text)` allowed it to download the controller zip file without throwing any exceptions.

This line does not exist in version 3.0, as it was for the new output I had for print statements in 3.1

**Comment by fayaz12g** [comment]
@IPaid4WinRAR thank you for sharing this, I’ve heard a few times people with different versions of python has persistent issues until they uninstall the previous version. I recognize this is not ideal so when I am home I will work on a version that doesn’t require python at all

**Comment by fayaz12g** [comment]
The new version doesn't need python
