### ISSUE TITLE
Cannot get it to work on steam deck

### ISSUE THREAD

**Issue by Dragonlord1005** [fayaz12g/totk-aar#80]
So, I configured the mod on my windows machine and tested it on there and all the ui for the steamdeck worked perfectly, but as I soon as I transfered it over to my steam deck it just wouldn't show up in the game.

**Comment by fayaz12g** [comment]
If it worked on your pc but not on your deck it's not an issue with the tool. I use windows on my deck and tested it working fine on there, as well as on steamOS. I recommend you try ensuring the mod folder you are adding it to is the correct mod folder, as well as making sure you are copying the right folder into there (the default name is Fayaz's settings)

**Comment by Dragonlord1005** [comment]
Turns out I wasn't copying over the right files, thank you for your assistance.
