### ISSUE TITLE
Error: File is not a zip file

### ISSUE THREAD

**Issue by DeltaQ-dze** [fayaz12g/totk-aar#81]
every time I run the program and try to get it to generate a mod, it just instantly fails with the message "Error: File is not a zip file"

**Comment by christiandenmark** [comment]
I'm getting the same issue. Trying to generate a mod for Playstation controller with white buttons on a western layout. When I hit generate it just fails with the message "Error: File is not a zip file" Still no fix?

**Comment by Pimpom12** [comment]
same here

**Comment by willsy32** [comment]
Same Issue.  Running as admin pulls same error

**Comment by robot-nick** [comment]
I have the same issue! Is there any fix for this? Tried deleting all old files in the directories, didn't work out

**Comment by Fruithapje21** [comment]
There seems to be an issue with the files at https://github.com/fayaz12g/aar-files/tree/main/totk, which is where the controller layout files are pulled from.

In the meantime you can get the aspect ratio mods from my repo: [TOTK-Ultrawide](https://github.com/Fruithapje21/TOTK-Ultrawide). The mods folder there includes files for most combinations of controller and aspect ratio.

**Comment by fayaz12g** [comment]
I honestly had no clue people still used my tools tbh. I stopped monitoring it and expiremented with git lfs that broke everything. I'll be reverting the commit now and the tool will work again @robot-nick

**Comment by fayaz12g** [comment]
I have tested the tool and it works again now. Sorry about that, I'm still honestly flabbergasted that people use this tool and it's making me want to continue refining them all of them. Not sure if you guys are aware of the AAR Launcher where my tools automatically update whenever I add fixes or new ones

**Comment by robot-nick** [comment]
@fayaz12g Thanks a lot! Amazing work!!
