### ISSUE TITLE
HUD fixes not working correctly on Ryujnx

### ISSUE THREAD

**Issue by Fruithapje21** [fayaz12g/totk-aar#83]
It's me! I wanted to give you quick heads up that some of the HUD fixes are not properly read/executed by Ryujinx. The corrected code can be found at https://github.com/Fruithapje21/TOTK-Ultrawide/tree/main/exefs_template

**Comment by fayaz12g** [comment]
Hey, long time since we've spoken! Thank you for letting me know :) I'll look into this
