### ISSUE TITLE
Some fixes and tips

### ISSUE THREAD

**Issue by Fl4sh9174** [fayaz12g/totk-aar#84]
On Splatoon 3, replace @true with @enabled to make it work at 2580x1080 resolution at 60fps on all areas.

Just fixed some issues with the old ar mod for Smash Bros Ultimate, better culing and improved the distance of some elements.

SMW3D and SMO were updated to use a more precise aspect ratio.

Mario Vs DK has some resolutions mods worth adding.

**Comment by fayaz12g** [comment]
@Fl4sh9174 thank you so much! I've been meaning to reach out to you to discuss how some of your fixes work, where is best? I really like your work

**Comment by Fl4sh9174** [comment]
On my Discord Fl4sh_#9174
