### ISSUE TITLE
pyautogui module not found

### ISSUE THREAD

**Issue by Servinjesus1** [fayaz12g/totk-aar#86]
Python within the launcher can't seem to find pyautogui. Tried installing it with pip but it's probably not using my local packages anyway, so it didn't work.

**Comment by synapp009** [comment]
Try older version. version 8.0.1 worked for me

**Comment by fayaz12g** [comment]
Hey sorry for the delay, are you guys running into this issue while using the AAR Launcher? I'm not able to recreate it, it is simply launching for me. Also what systems are you running, I assume Windows 11? @synapp009 @Servinjesus1

**Comment by synapp009** [comment]
Don't worry for the delay.younare correct, I use Windows 11 @fayaz12g

**Comment by fayaz12g** [comment]
Thank you @synapp009, I'm going to try incorporating pyautogui directly into the launcher tomorrow (it's almost 3 am for me). I'm mainly confused because other have been able to launch it just fine as is but we'll see if that fixes it for y'all!

**Comment by Gentleman358** [comment]
I am getting the same error, but I am using windows 10

**Comment by fayaz12g** [comment]
Hey guys, sorry for taking so long. The issue should be fixed now, on the latest build here: https://github.com/fayaz12g/aar-launcher/releases/download/10.22.24/AAR_Debug.zip

@Gentleman358 @synapp009 @Servinjesus1
