### ISSUE TITLE
The 'Breath of the Wild' function is malfunctioning

### ISSUE THREAD

**Issue by Medekaisa** [fayaz12g/totk-aar#87]
Using AAR When clicking on 'Breath of the wild' in Launcher. exe, there is no response when clicking on 'Generate'. Please find a solution

**Comment by fayaz12g** [comment]
Hello, it has been fixed, the tool now works on Breath of the Wild. I am still working on the shifting function for corner hud i will let you know when it was done, but in the mean time please enjoy center hud
